// Code generated by "stringer -type ExpressionKind"; DO NOT EDIT.

package pattern

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EXPRESSION_LITERAL-0]
	_ = x[EXPRESSION_CLASS-1]
	_ = x[EXPRESSION_CONCAT-2]
	_ = x[EXPRESSION_UNION-3]
	_ = x[EXPRESSION_REPEAT-4]
}

const _ExpressionKind_name = "EXPRESSION_LITERALEXPRESSION_CLASSEXPRESSION_CONCATEXPRESSION_UNIONEXPRESSION_REPEAT"

var _ExpressionKind_index = [...]uint8{0, 18, 34, 51, 67, 84}

func (i ExpressionKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ExpressionKind_index)-1 {
		return "ExpressionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpressionKind_name[_ExpressionKind_index[idx]:_ExpressionKind_index[idx+1]]
}
