// Code generated by "stringer -type VistraKind"; DO NOT EDIT.

package pattern

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VistraAtom-1]
	_ = x[VistraClass-2]
	_ = x[VistraConcat-3]
	_ = x[VistraUnion-4]
	_ = x[VistraRepeat-5]
	_ = x[VistraNest-6]
	_ = x[VistraEmpty-7]
}

const _VistraKind_name = "VistraAtomVistraClassVistraConcatVistraUnionVistraRepeatVistraNestVistraEmpty"

var _VistraKind_index = [...]uint8{0, 10, 21, 33, 44, 56, 66, 77}

func (i VistraKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_VistraKind_index)-1 {
		return "VistraKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VistraKind_name[_VistraKind_index[idx]:_VistraKind_index[idx+1]]
}
